- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.128.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
  
    - name: create .kube directory
      become: yes
      become_user: root
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
  
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
  
    - name: install Pod network
      become: yes
      become_user: root
      shell: kubectl apply -f https://raw.githubusercontent.com/thinkub/ansible-k8s-cluster/master/flannel.yml
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
